# Generated by Django 2.1.2 on 2018-11-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181031_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='task_name',
        ),
    ]
