# Generated by Django 2.1.2 on 2018-11-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181101_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.TextField(max_length=100),
        ),
    ]
