# Generated by Django 2.1.2 on 2018-11-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181103_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_name',
            new_name='taskAdd',
        ),
    ]
