# Generated by Django 2.1.2 on 2018-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181104_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectAdd', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
